### ISSUE TITLE
custom prompt strings

### ISSUE THREAD

**Issue by rsgalloway** [rsgalloway/envstack#10]
customize the prompt string $PS1 / %PROMPT% to display the current stack or environment.

something like this could be added to the stack file:

```yaml
linux:
  <<: *default
  PS1: "[${ENV}] ${PS1}"

windows:
  <<: *default
  PROMPT: "[${ENV}] ${PROMPT}"
```

but I think what we want is the stack name:

```bash
(.venv) user@hostname:/current/directory$ envstack-init
[stack] (.venv) user@hostname:/current/directory$ envstack-init dev
[dev] (.venv) user@hostname:/current/directory$ 
```
