### ISSUE TITLE
resolving >3 levels of indirection

### ISSUE THREAD

**Issue by rsgalloway** [rsgalloway/envstack#59]
three levels of indirection seems to resolve correctly, however, more than that and we get unexpected results:

4 levels of indirection:
```yaml
  VAR: ${VAR:=${FOO}}
  FOO: ${FOO:=${BAR}}
  BAR: ${BAZ:=bar}
  BAZ: ${QUX}
  QUX: foo
```

results:
```bash
BAR=bar
BAZ=foo
FOO=bar
QUX=foo
VAR=bar
```

expected results:
```bash
BAR=foo
BAZ=foo
FOO=bar
QUX=foo
VAR=foo
```

**Comment by rsgalloway** [comment]
if we remove the expansion modifiers, we still get unexpected results:

```yaml
  VAR: ${VAR}
  FOO: ${FOO}
  BAR: ${BAZ}
  BAZ: ${QUX}
  QUX: foo
```

results:
```bash
BAR=foo
BAZ=foo
FOO=
QUX=foo
VAR=
```
