### ISSUE TITLE
TypeError on inherited int values

### ISSUE THREAD

**Issue by rsgalloway** [rsgalloway/envstack#62]
int values set in included envs get a TypeError and return the original expression:

parent.env
```yaml
include: []
all: &all
  NUM: 1
```

child.env
```yaml
include: [parent]
all: &all
  NUM: ${NUM:=0}
```

the resolved value of NUM is:

```bash
$ ./child.env -r
NUM=${NUM:=0}
```

the expected value is 1.

it seems that this only happens on int values, and a TypeError is thrown and the original expression gets returned:

```python
result = variable_pattern.sub(substitute_variable, expression)
TypeError: sequence item 0: expected str instance, int found
```
